# Generated by Django 5.0.2 on 2025-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
